### ISSUE TITLE
[Forum] Login page keyboard shortcut

### ISSUE THREAD

**Issue by WoutProvost** [openmultiplayer/todo#20]
https://www.burgershot.gg/member.php?action=login
When you're on this page, I'd like to just press ENTER to send the form.

**Comment by Southclaws** [comment]
This works, and it should because the `<input>` is within the `<form>` and has `type="submit"`.

**Comment by WoutProvost** [comment]
When using a browser or extension autofiller, it doesn't apply focus to any of the 2 input fields, so you still have to move your mouse and click. This can be easily fixed by applying focus to either one of the input fields or the button.

Example with JQuery:
```Javascript
$(".trow1").find("input[type=text]").focus();
// Or
$(".button").focus();
```

**Comment by Southclaws** [comment]
Ah I see what you mean now. Yeah that can be done.

It doesn't need jQuery either, you can do that with the standard library:

```js
document.querySelector(".button").focus()
```

**Comment by WoutProvost** [comment]
Done
